### ISSUE TITLE
Way to specify resource files (JSON, YAML, or INI)

### ISSUE THREAD

**Issue by Descent098** [Descent098/pystall#12]
Going to standardize on YML for now, will look at JSON and INI later.

Here is the current max and min spec:

```yml
Resources:
  "python":
    type: "exe"
    location: "https://www.python.org/ftp/python/3.8.1/python-3.8.1.exe"
    arguments: ["-a", "-b", "-c"]
    downloaded: false
    remove: true
    overwrite_agreement: false
  "golang"
    type: "ppa"
    PPA: "ppa:longsleep/golang-backports"
    packages: ["golang-go"]

  "git":
    type: "apt"
    packages: ["git"]
    # Dependencies are not specified because you can just order them as a resource yourself
```

TODO
- [x] Write a read --> preprocess/validation --> build pipeline
- [x] Write inline docs
- [x] Write user docs
